apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls-cluster
  namespace: cert-manager
spec:
  secretName: wildcard-tls-cluster
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - "example.com"
    - "*.example.com"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
