#
# https://cert-manager.io/docs/installation/helm/ ->
# -> https://cert-manager.io/docs/installation/kubectl/#verify
#

apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-test

---

#
# kubectl get issuers -n cert-manager-test test-selfsigned
#

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: cert-manager-test
spec:
  selfSigned: {}

---

#
# kubectl get certs -n cert-manager-test selfsigned-cert -o yaml
# + kubectl get crs -n cert-manager-test selfsigned-cert-1 -o yaml
# + kubectl get secrets -n cert-manager-test selfsigned-cert-tls
#

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: cert-manager-test
spec:
  dnsNames:
    - example.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned

---

#
# https://cert-manager.io/docs/concepts/issuer/
# https://cert-manager.io/docs/configuration/ca/
#

# k3s example (simplified testing in development):
#
# k3s kubectl create secret tls k3s-client-ca \
#   -n cert-manager-test \
#   --key=/var/lib/rancher/k3s/server/tls/client-ca.key \
#   --cert=/var/lib/rancher/k3s/server/tls/client-ca.crt

#apiVersion: v1
#data:
#  tls.crt: LS0tLS1CRUdJ...
#  tls.key: LS0tLS1CRUdJ...
#kind: Secret
#metadata:
#  name: test-ca-local
#  namespace: cert-manager-test
#type: kubernetes.io/tls
#---
#apiVersion: cert-manager.io/v1
#kind: Issuer
#metadata:
#  name: test-ca-local
#  namespace: cert-manager-test
#spec:
#  ca:
#    secretName: test-ca-local
#---
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: local-cert
#  namespace: cert-manager-test
#spec:
#  dnsNames:
#    - example.com
#  secretName: local-cert
#  issuerRef:
#    name: test-ca-local
