#
# ref: https://doc.traefik.io/traefik/reference/install-configuration/entrypoints/
#
# "--entrypoints.web.http.redirections.entryPoint.to=websecure" doesn't work
# because redir to :8443 is done (internal port) instead of :443 (public port)
#

apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--api.insecure=true"
      - "--entrypoints.web.http.redirections.entryPoint.to=:443"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
