apiVersion: v1
kind: Namespace
metadata:
  name: i12e
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anki-sync-server
  namespace: i12e
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anki-sync-server
  template:
    metadata:
      labels:
        app: anki-sync-server
    spec:
      containers:
      - name: anki-sync-server
        image: ghcr.io/sfmunoz/anki-sync-server:{{ .Version }}
        ports:
        - containerPort: 8080
        env:
        {{- range $i, $u := .SyncUsers }}
        - name: SYNC_USER{{ add $i 1 }}
          value: {{ $u.User }}:{{ $u.Pass }}
        {{- end }}
        volumeMounts:
        - name: data
          mountPath: /anki_data/
      volumes:
      - name: data
        hostPath:
          path: /opt/anki-sync-server
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: anki-sync-server
  namespace: i12e
spec:
  selector:
    app: anki-sync-server
  ports:
  - port: 8080
    targetPort: 8080
