#
# https://cert-manager.io/docs/installation/helm/
#

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  chart: oci://quay.io/jetstack/charts/cert-manager
  version: v1.21.1
  targetNamespace: cert-manager
  createNamespace: true
  set:
    crds.enabled: "true"

---

#
# https://kubernetes.recipes/recipes/security/certmanager-ovh-dns01-wildcard-tls/
#

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager-webhook-ovh
  namespace: kube-system
spec:
  chart: cert-manager-webhook-ovh
  repo: https://aureq.github.io/cert-manager-webhook-ovh
  version: 0.9.15
  targetNamespace: cert-manager
  createNamespace: true
  valuesContent: |
    groupName: acme.i12e

---

#
# https://cert-manager.io/docs/installation/helm/ -> -> https://cert-manager.io/docs/installation/kubectl/#verify
#

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-selfsigned
  namespace: cert-manager
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-selfsigned
  namespace: cert-manager
spec:
  dnsNames:
    - cert.local
  secretName: cert-selfsigned
  issuerRef:
    name: cert-manager-selfsigned

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-k3s-client
  namespace: cert-manager
spec:
  ca:
    secretName: k3s-client-ca

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-k3s-client
  namespace: cert-manager
spec:
  dnsNames:
    - cert.local
  secretName: cert-k3s-client
  issuerRef:
    name: cert-manager-k3s-client

---

apiVersion: v1
data:
  applicationKey: {{ .Ak }}
  applicationSecret: {{ .As }}
  consumerKey: {{ .Ck }}
kind: Secret
metadata:
  name: ovh-credentials
  namespace: cert-manager

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-webhook-ovh-secret-reader
  namespace: cert-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["ovh-credentials"]
    verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-ovh-secret-reader
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-webhook-ovh-secret-reader
subjects:
  - kind: ServiceAccount
    name: cert-manager-webhook-ovh
    namespace: cert-manager

