# https://docs.k3s.io/add-ons/helm
# https://docs.k3s.io/installation/packaged-components
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: postgres-rclone
  namespace: kube-system
spec:
  chart: oci://ghcr.io/sfmunoz/postgres-rclone
  version: "{{ .Version }}"
  targetNamespace: "{{ .Namespace }}"
  createNamespace: true
  valuesContent: |-
    rclone:
      conf: |
        [rem]
        remote = rustfs:d01
        type = alias
        [rustfs]
        acl = private
        endpoint = http://192.168.56.1:9000
        provider = Other
        secret_access_key = rustfsadmin
        type = s3
        access_key_id = rustfsadmin
    postgres:
      password: changeme_now
