apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts
  namespace: trilium
data:
  rclone-pull.sh: |
    #!/bin/sh
    set -x
    exec rclone sync -v --transfers 1 --stats 10s rem:trilium /backup
  rclone-push.sh: |
    #!/bin/sh
    set -x
    exec rclone sync -v --transfers 1 --stats 10s /backup rem:trilium
  restore-lock.sh: |
    #!/bin/sh
    echo "backup locked: follow these steps:"
    echo "- 1. kubectl exec -it -c restore -n trilium deploy/trilium -- sh"
    echo "- 2. setup '${DATA_FOLDER}' with proper contents (may be empty)"
    echo "- 3. rm -f /backup/i12e.lock (before using 'backup-one.sh' or it will lock again)"
    echo "- 4. /bin/sh /scripts/backup-one.sh"
    echo "- 5. pkill tail -> kill 'tail -f /dev/null' process to start over"
    set -x
    tail -f /dev/null &
    wait $!
    exit 1
  restore-main.sh: |
    #!/bin/sh
    set -x -e -o pipefail
    date
    ln -s /tools/restic /usr/local/bin/restic
    ln -s /tools/rclone /usr/local/bin/rclone
    date
    /bin/sh /scripts/rclone-pull.sh
    date
    [ -f "/backup/i12e.lock" ] && exec /bin/sh /scripts/restore-lock.sh
    date
    restic check
    date
    restic snapshots -g tag
    date
    restic backup -vv --tag boot "${DATA_FOLDER}"
    date
    /bin/sh /scripts/rclone-push.sh
    date
    rm -rfv "${DATA_FOLDER}/"*
    date
    restic restore -vv --tag main -t / latest
    date
    [ -f "${DATA_FOLDER}/.bhooks/post-restore-main.sh" ] && /bin/sh "${DATA_FOLDER}/.bhooks/post-restore-main.sh"
    date
  backup-one.sh: |
    #!/bin/sh
    set -x -e -o pipefail
    date
    [ -f "${DATA_FOLDER}/.bhooks/pre-backup-one.sh" ] && /bin/sh "${DATA_FOLDER}/.bhooks/pre-backup-one.sh"
    date
    [ -f "$${RESTIC_REPOSITORY}/config" ] || restic init
    date
    restic backup -vv --tag main "${DATA_FOLDER}"
    date
    /bin/sh /scripts/rclone-push.sh
    date
    [ -f "${DATA_FOLDER}/.bhooks/post-backup-one.sh" ] && /bin/sh "${DATA_FOLDER}/.bhooks/post-backup-one.sh"
    date
  backup-forget.sh: |
    #!/bin/sh
    set -x -e -o pipefail
    restic forget -vv -g tag -l 24 -H 48 -d 7 -w 4 -m 6 --prune
    date
    /bin/sh /scripts/rclone-push.sh
    date
  backup-at-exit.sh: |
    #!/bin/sh
    echo "Exit requested..."
    set -x -e -o pipefail
    date
    [ -f "/backup-blocked" ] && exit 0
    date
    [ -f "${DATA_FOLDER}/.bhooks/pre-backup-at-exit.sh" ] && /bin/sh "${DATA_FOLDER}/.bhooks/pre-backup-at-exit.sh"
    date
    /bin/sh /scripts/backup-one.sh
    date
    [ -f "${DATA_FOLDER}/.bhooks/post-backup-at-exit.sh" ] && /bin/sh "${DATA_FOLDER}/.bhooks/post-backup-at-exit.sh"
    date
  backup-main.sh: |
    #!/bin/sh
    set -x -e -o pipefail
    ln -s /tools/restic /usr/local/bin/restic
    ln -s /tools/rclone /usr/local/bin/rclone
    trap "exec /bin/sh /scripts/backup-at-exit.sh" TERM
    while true
    do
      date
      sleep $((3300 + RANDOM % 600))
      [ -f "/backup-blocked" ] && continue
      /bin/sh /scripts/backup-one.sh
      /bin/sh /scripts/backup-forget.sh
    done &
    wait $!
