apiVersion: v1alpha1
kind: KubeNodeConfig
nodeIP:
  validSubnets:
  - 192.168.186.0/24
---
# https://docs.siderolabs.com/talos/v1.14/networking/ingress-firewall
apiVersion: v1alpha1
kind: NetworkDefaultActionConfig
ingress: block
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: wireguard
portSelector:
  ports:
    - 51823
  protocol: udp
ingress:
  - subnet: 192.168.56.0/24
---
# kind: KubeNetworkConfig
# podSubnets: [10.244.0.0/16]
# serviceSubnets: [10.96.0.0/12]
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: kubelet-ingress
portSelector:
  ports:
    - 10250
  protocol: tcp
ingress:
  - subnet: 192.168.186.0/24
  - subnet: 10.244.0.0/16  # coredns health check would fail when on control-plane
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: cni-vxlan
portSelector:
  ports:
    - 4789
  protocol: udp
ingress:
  - subnet: 192.168.186.0/24
---
# https://docs.siderolabs.com/talos/v1.14/networking/configuration/overview
# Note: Default Talos Linux behavior to run DHCP on any physical link is disabled
# automatically when any link is configured explicitly in the machine configuration.
# In order to keep DHCP running, it must be explicitly enabled on the desired link(s).
apiVersion: v1alpha1
kind: DHCPv4Config
name: enp0s3
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: enp0s8
---
# https://docs.siderolabs.com/kubernetes-guides/csi/local-storage
# https://docs.siderolabs.com/talos/v1.14/configure-your-talos-cluster/storage-and-disk-management/disk-management/user
apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-path-provisioner
volumeType: directory
---
# https://docs.siderolabs.com/kubernetes-guides/monitoring-and-observability/deploy-metrics-server#after-bootstrap
apiVersion: v1alpha1
kind: KubeletConfig
extraArgs:
  rotate-server-certificates: true
