#
# Ref: https://github.com/fluxcd/flux2-kustomize-helm-example/blob/main/clusters/production/artifacts.yaml
#

---
apiVersion: source.extensions.fluxcd.io/v1beta1
kind: ArtifactGenerator
metadata:
  name: flux-system
  namespace: flux-system
spec:
  sources:
    - alias: monorepo
      kind: GitRepository
      name: flux-system
  artifacts:
    - name: infra
      originRevision: "@monorepo"
      copy:
        - from: "@monorepo/infra/dev/**"
          to: "@artifact/infra/"
    - name: apps
      originRevision: "@monorepo"
      copy:
        - from: "@monorepo/apps/dev/**"
          to: "@artifact/apps/"
---
apiVersion: source.extensions.fluxcd.io/v1beta1
kind: ArtifactGenerator
metadata:
  name: flux-system
  namespace: flux-secrets
spec:
  sources:
    - alias: secretsrepo
      kind: GitRepository
      name: flux-secrets
  artifacts:
    - name: secrets
      originRevision: "@secretsrepo"
      copy:
        - from: "@secretsrepo/clusters/dev/**"
          to: "@artifact/secrets/"
