---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-secrets
  namespace: flux-system
spec:
  interval: 29m07s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/sfmunoz/i12e-secrets.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-secrets
  namespace: flux-system
spec:
  dependsOn:
  - name: infra
    namespace: flux-system
  interval: 9m47s
  path: ./secrets
  prune: true
  sourceRef:
    kind: ExternalArtifact
    name: flux-secrets
  decryption:
    provider: sops
    secretRef:
      name: sops-age
