apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: anki-sync-server
  namespace: anki
spec:
  interval: 17m22s
  chart:
    spec:
      chart: ./apps/prod/anki/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: anki-sync-server-conf
      valuesKey: values.yaml
