apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anki
  namespace: anki
spec:
  accessModes:
    - ReadWriteOncePod
  storageClassName: local-path
  resources:
    requests:
      storage: 128Mi
