apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: certs
  namespace: cert-manager
spec:
  interval: 17m12s
  timeout: 15m0s
  chart:
    spec:
      chart: ./apps/dev/cert-manager/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: certs-config
      valuesKey: values.yaml
