apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certs
  namespace: cert-manager
spec:
  interval: 10m38s
  sourceRef:
    kind: ExternalArtifact
    name: apps
    namespace: flux-system
  path: ./apps/cert-manager/certs
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: certs-config
        optional: false
