apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rem-multi
  namespace: i12e
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rem-multi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rem-fs
  namespace: i12e
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rem-fs
