{%- if i12e_mode in ["main","server"] -%}
token: "{{ k3s_token }}"
agent-token: "{{ k3s_agent_token }}"
secrets-encryption: true
secrets-encryption-provider: secretbox
flannel-backend: "wireguard-native"

{%- if tls_san is defined %}
tls-san: "{{ tls_san }}"
{%- endif -%}

{%- if i12e_mode == "main" %}
cluster-init: true
{%- else %}
server: "{{ k3s_url }}"
{%- endif -%}

{%- else -%}
token: {{ k3s_agent_token }}
server: "{{ k3s_url }}"
{%- endif -%}
