# nft list table inet filter
table inet filter {
  chain input {
    type filter hook input priority raw; policy accept;
    iifname {"eth*"} jump input_public
    counter
  }
  chain forward {
    type filter hook forward priority raw; policy accept;
    counter
  }
  chain output {
    type filter hook forward priority raw; policy accept;
    counter
  }
  chain input_public {
    meta l4proto {tcp,udp} ct state { established, related } counter accept
    meta l4proto ipv6-icmp counter accept  # XXX: don't block it: IPv6 doesn't work otherwise (doesn't seem to move from private to public IP)
    meta l4proto icmp counter accept
    meta l4proto {tcp} th dport {22} ct state {new} counter accept       # both ipv4/ipv6
    counter reject
  }
}
