# nft list table inet filter
table inet filter {
  chain input {
    type filter hook input priority -300; policy accept;
    meta l4proto icmp iifname "eth*" counter reject
    counter return
  }
  chain forward {
    type filter hook forward priority -300; policy accept;
    counter return
  }
  chain output {
    type filter hook forward priority -300; policy accept;
    counter return
  }
}
