#
# Ref: https://github.com/fluxcd/flux2-kustomize-helm-example/blob/main/clusters/production/apps.yaml
#

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
  - name: infra
    namespace: flux-system
  - name: flux-secrets
    namespace: flux-system
  interval: 9m16s
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: ExternalArtifact
    name: apps
  path: ./apps
  prune: true
  wait: true
