apiVersion: v1
kind: Pod
metadata:
  name: spark
spec:
  restartPolicy: Never
  containers:
  - name: spark
    image: ghcr.io/sfmunoz/k8s-bulk:v1.3.0
    imagePullPolicy: IfNotPresent
    command: ["python3","-u","-c"]
    args:
    - |
      {{- include "spark.py" . | nindent 6 }}
    volumeMounts:
    - mountPath: /spark
      name: vol-host
      readOnly: false
  volumes:
  - name: vol-host
    hostPath:
      path: /
      type: Directory
