apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: http-8000
  namespace: gateways
spec:
  gatewayClassName: traefik
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: http
    port: 8000
    protocol: HTTP
