apiVersion: apps/v1
kind: Deployment
metadata:
  name: trilium
  namespace: trilium
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: trilium
  template:
    metadata:
      labels:
        app: trilium
    spec:
      #terminationGracePeriodSeconds: 20
      initContainers:
      - name: rclone
        image: "rclone/rclone:sha-6805da6"
        command: ["/bin/sh","-x","-c","cp /usr/local/bin/rclone /tools/rclone"]
        volumeMounts:
        - name: tools
          mountPath: /tools
      - name: restic
        image: "restic/restic:0.19.1"
        command: ["/bin/sh","-x","-c","cp /usr/bin/restic /tools/restic"]
        volumeMounts:
        - name: tools
          mountPath: /tools
      - name: restore
        image: "triliumnext/trilium:v0.104.0"
        env:
        - name: RESTIC_REPOSITORY
          value: "/backup"
        - name: RESTIC_PASSWORD_FILE
          value: "/restic-conf/password.txt"
        command: ["/bin/sh","-x","-c","date >> /home/node/trilium-data/restore.log"]
        volumeMounts:
        - name: tools
          mountPath: /tools
          readOnly: true
        - name: data
          mountPath: /home/node/trilium-data/
        - name: backup
          mountPath: /backup
        - name: restic-conf
          mountPath: /restic-conf
          readOnly: true
        - name: rclone-conf
          mountPath: /root/.config/rclone
          readOnly: true
      containers:
      - name: main
        image: "triliumnext/trilium:v0.104.0"
        env:
        - name: TRILIUM_PORT
          value: "8080"   # default set by K8S: something like 'tcp://10.43.167.120:8080'
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: tools
          mountPath: /tools
          readOnly: true
        - name: data
          mountPath: /home/node/trilium-data/
      - name: backup
        image: "triliumnext/trilium:v0.104.0"
        env:
        - name: RESTIC_REPOSITORY
          value: "/backup"
        - name: RESTIC_PASSWORD_FILE
          value: "/restic-conf/password.txt"
        command: ["/bin/sh","-c"]
        args:
        - |
          function callback {
            echo "$(date) exiting..."
            exit 0
          }
          set -x
          trap callback TERM
          tail -f /dev/null &
          child="$!"
          wait "$child"
        volumeMounts:
        - name: tools
          mountPath: /tools
          readOnly: true
        - name: data
          mountPath: /home/node/trilium-data/
          readOnly: true
        - name: backup
          mountPath: /backup
        - name: restic-conf
          mountPath: /restic-conf
          readOnly: true
        - name: rclone-conf
          mountPath: /root/.config/rclone
          readOnly: true
      volumes:
      - name: tools
        emptyDir: {}
      - name: data
        persistentVolumeClaim:
          claimName: trilium-data
      - name: backup
        persistentVolumeClaim:
          claimName: trilium-backup
      - name: restic-conf
        secret:
          secretName: restic-conf
          items:
          - key: password
            path: password.txt
      - name: rclone-conf
        secret:
          secretName: rclone-conf
          items:
          - key: configData
            path: rclone.conf
