apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${APPNAME}
  namespace: ${NAMESPACE}
spec:
  tls:
  - secretName: "${SECRETNAME}"
    hosts:
    - "${HOSTNAME}"
  rules:
  - host: "${HOSTNAME}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ${APPNAME}
            port:
              number: 8080
