apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trilium-data
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteOncePod
  storageClassName: local-path
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trilium-backup
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteOncePod
  storageClassName: local-path
  resources:
    requests:
      storage: 256Mi
