apiVersion: apps/v1
kind: Deployment
metadata:
  name: trilium
  namespace: trilium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trilium
  template:
    metadata:
      labels:
        app: trilium
    spec:
      #terminationGracePeriodSeconds: 20
      initContainers:
      - name: rclone
        image: "rclone/rclone:sha-6805da6"
        command: ["/bin/sh","-x","-c","cp /usr/local/bin/rclone /tools/rclone"]
        volumeMounts:
        - name: tools
          mountPath: /tools
          readOnly: false
      - name: restic
        image: "restic/restic:0.19.1"
        command: ["/bin/sh","-x","-c","cp /usr/bin/restic /tools/restic"]
        volumeMounts:
        - name: tools
          mountPath: /tools
          readOnly: false
      containers:
      - name: trilium
        image: "triliumnext/trilium:v0.104.0"
        env:
        - name: TRILIUM_PORT
          value: "8080"   # default set by K8S: something like 'tcp://10.43.167.120:8080'
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: tools
          mountPath: /tools
          readOnly: true
        - name: data
          mountPath: /home/node/trilium-data/
      volumes:
      - name: tools
        emptyDir: {}
      - name: data
        persistentVolumeClaim:
          claimName: trilium
