apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-b
  namespace: forgejo
spec:
  interval: 11m29s
  sourceRef:
    kind: ExternalArtifact
    name: apps
    namespace: flux-system
  path: ./apps/forgejo/b
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-s
  namespace: flux-system
spec:
  dependsOn:
  - name: forgejo-b
    namespace: forgejo
  interval: 11m36s
  sourceRef:
    kind: ExternalArtifact
    name: secrets
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./secrets/forgejo
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-w
  namespace: forgejo
spec:
  dependsOn:
  - name: forgejo-b
    namespace: forgejo
  - name: forgejo-s
    namespace: flux-system
  - name: gateways
    namespace: gateways
  interval: 11m56s
  sourceRef:
    kind: ExternalArtifact
    name: apps
    namespace: flux-system
  path: ./apps/forgejo/w
  prune: true
  wait: true
  postBuild:
    substitute:
      DOCKER_IMAGE: codeberg.org/forgejo/forgejo:16.0.3
      APPNAME: forgejo
      NAMESPACE: forgejo
      DATA_FOLDER: /data
    substituteFrom:
      - kind: Secret
        name: routes-conf
        optional: false
