#
# Ref: https://github.com/fluxcd/flux2-kustomize-helm-example/blob/main/clusters/production/artifacts.yaml
#

---
apiVersion: source.extensions.fluxcd.io/v1beta1
kind: ArtifactGenerator
metadata:
  name: flux-system
  namespace: flux-system
spec:
  sources:
    - alias: monorepo
      kind: GitRepository
      name: flux-system
    - alias: secretsrepo
      kind: GitRepository
      name: secrets
  artifacts:
    - name: clusters
      originRevision: "@monorepo"
      copy:
        - from: "@monorepo/clusters/dev/**"
          to: "@artifact/clusters/"
    - name: blend
      copy:
        - from: "@secretsrepo/clusters/dev/**"
          to: "@artifact/blend/"
        - from: "@monorepo/apps/dev/**"
          to: "@artifact/blend/"
    - name: blend-scripts
      copy:
        - from: "@monorepo/apps/dev/common/**"
          to: "@artifact/blend/anki"
        - from: "@monorepo/apps/dev/common/**"
          to: "@artifact/blend/forgejo"
        - from: "@monorepo/apps/dev/common/**"
          to: "@artifact/blend/trilium"
        - from: "@secretsrepo/clusters/dev/**"
          to: "@artifact/blend/"
        - from: "@monorepo/apps/dev/**"
          to: "@artifact/blend/"
