apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-rclone
  namespace: csi-rclone
spec:
  chartRef:
    kind: OCIRepository
    name: csi-rclone
    namespace: csi-rclone
  interval: 10m53s
