package node

import (
	"fmt"
	"net/netip"
	"os"
	"os/exec"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/sfmunoz/i12e/internal/cmdutil"
	"github.com/sfmunoz/i12e/internal/mesh/wgkey"
)

const nodeInterface = "wgi"
const nodePrivKeyFname = "/etc/i12e/wg-priv-key"
const nodeEtcHostname = "/etc/hostname"

var nodeNet = func() *netip.Prefix {
	x := netip.MustParsePrefix("10.119.0.0/16") // '/16' is mandatory (hardcoded for now)
	return &x
}()

func GetNodeInterface() string {
	return nodeInterface
}

func padLeft(s string, tot int, pad string) string {
	if len(s) >= tot {
		return s
	}
	return strings.Repeat(pad, tot-len(s)) + s
}

type Node struct {
	id         uint16 // uint16 instead of byte to avoid pervasive type conversion
	wgKey      *wgkey.WgKey
	wgEndpoint *netip.AddrPort
}

func (n *Node) tuple() [2]byte {
	return [2]byte{byte(n.id / 256), byte(n.id % 256)}
}

func (n *Node) String() string {
	return fmt.Sprintf(
		"id=%d|name=%s|ip=%s|local=%t|wgkey=%s",
		n.GetNodeId(),
		n.GetNodeName(),
		n.GetNodeIP(),
		n.GetLocal(),
		n.GetWgKey(),
	)
}

func (n *Node) GetNodeId() uint16 {
	return n.id
}

func (n *Node) GetNodeName() string {
	s := strconv.FormatUint(uint64(n.GetNodeId()), 36) // 36^4 > 2^20
	return "n" + padLeft(s, 4, "0")
}

func (n *Node) GetNodeIP() *netip.Addr {
	x := nodeNet.Addr().As4()
	t := n.tuple()
	addr := netip.AddrFrom4([4]byte{x[0], x[1], t[0], t[1]})
	return &addr
}

func (n *Node) GetWgKey() *wgkey.WgKey {
	return n.wgKey
}

func (n *Node) GetLocal() bool {
	return n.GetWgKey().GetLocal()
}

func (n *Node) GetWgEndpoint() *netip.AddrPort {
	return n.wgEndpoint
}

func (n *Node) HostnameConfig() error {
	if err := os.WriteFile(nodeEtcHostname, fmt.Appendf(make([]byte, 0), "%s\n", n.GetNodeName()), 0644); err != nil {
		return err
	}
	cmd := exec.Command("hostname", "-F", nodeEtcHostname)
	bo, be, err := cmdutil.RunSimple(cmd)
	if err != nil {
		return fmt.Errorf("SetHostname(): 'hostname -F' failed': %s (stdout=%s, stderr=%s)", err, bo.String(), be.String())
	}
	return nil
}

func (n *Node) IfaceLocalConfig() error {
	nodeInt := GetNodeInterface()
	cmd := exec.Command("ip", "link", "set", nodeInt, "down")
	bo, be, err := cmdutil.RunSimple(cmd)
	// ignore error: it's OK
	cmd = exec.Command("ip", "link", "del", nodeInt)
	bo, be, err = cmdutil.RunSimple(cmd)
	// ignore error: it's OK
	cmd = exec.Command("ip", "link", "add", nodeInt, "type", "wireguard")
	bo, be, err = cmdutil.RunSimple(cmd)
	if err != nil {
		return fmt.Errorf("'ip link add' failed': %s (stdout=%s, stderr=%s)", err, bo.String(), be.String())
	}
	cmd = exec.Command("ip", "addr", "add", fmt.Sprintf("%s/%d", n.GetNodeIP(), nodeNet.Bits()), "dev", nodeInt)
	bo, be, err = cmdutil.RunSimple(cmd)
	if err != nil {
		return fmt.Errorf("'ip link add' failed': %s (stdout=%s, stderr=%s)", err, bo.String(), be.String())
	}
	cmd = exec.Command("wg", "set", nodeInt, "listen-port", fmt.Sprintf("%d", n.GetWgEndpoint().Port()), "private-key", nodePrivKeyFname)
	bo, be, err = cmdutil.RunSimple(cmd)
	if err != nil {
		return fmt.Errorf("'wg set' failed': %s (stdout=%s, stderr=%s)", err, bo.String(), be.String())
	}
	cmd = exec.Command("ip", "link", "set", nodeInt, "up")
	bo, be, err = cmdutil.RunSimple(cmd)
	if err != nil {
		return fmt.Errorf("'ip link set' failed': %s (stdout=%s, stderr=%s)", err, bo.String(), be.String())
	}
	return nil
}

func (n *Node) EtcHostsUpdate(nodeList []*Node) error {
	// Flatcar's default
	lines := []string{
		"#",
		"# autogenerated by i12e - do not edit",
		"#",
		"",
		"127.0.0.1 localhost",
		"::1 localhost",
	}
	for _, n := range nodeList {
		lines = append(lines, fmt.Sprintf("%s %s", n.GetNodeIP(), n.GetNodeName()))
	}
	lines = append(lines, "") // NL to the end
	buf := strings.Join(lines, "\n")
	return os.WriteFile("/etc/hosts", []byte(buf), 0644)
}

func (n *Node) pushToRemote(remMeshBase string) error {
	if !n.GetLocal() {
		return fmt.Errorf("cannot push node: it's not local")
	}
	ts := time.Now().UTC()
	nodeName := n.GetNodeName()
	wgEndpoint := n.GetWgEndpoint()
	touchPath := fmt.Sprintf(
		"%s/%s/%s_%09d/%s/%s/%d",
		remMeshBase,
		nodeName,
		ts.Format("20060102_150405"),
		ts.Nanosecond(),
		n.GetWgKey().GetPubKey().Hex(),
		wgEndpoint.Addr(),
		wgEndpoint.Port(),
	)
	cmd := exec.Command("rclone", "touch", touchPath)
	bo, be, err := cmdutil.RunSimple(cmd)
	if err != nil {
		return fmt.Errorf("'rclone touch' failed': %s (stdout=%s, stderr=%s)", err, bo.String(), be.String())
	}
	nodePrefix := fmt.Sprintf("%s/%s", remMeshBase, nodeName)
	cmd = exec.Command("rclone", "lsf", nodePrefix)
	bo, be, err = cmdutil.RunSimple(cmd)
	if err != nil {
		return fmt.Errorf("'rclone lsf' failed': %s (stdout=%s, stderr=%s)", err, bo.String(), be.String())
	}
	entries := strings.Split(strings.TrimSpace(bo.String()), "\n")
	slices.Sort(entries)
	slices.Reverse(entries)
	for i, entry := range entries {
		if i < 1 {
			continue
		}
		deletePath := fmt.Sprintf("%s/%s/%s", remMeshBase, nodeName, entry)
		cmd := exec.Command("rclone", "delete", deletePath)
		bo, be, err := cmdutil.RunSimple(cmd)
		if err != nil {
			return fmt.Errorf("'rclone delete' failed': %s (stdout=%s, stderr=%s)", err, bo.String(), be.String())
		}
	}
	return nil
}
