apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wikijs-b
  namespace: flux-system
spec:
  interval: 11m42s
  sourceRef:
    kind: ExternalArtifact
    name: apps
    namespace: flux-system
  path: ./apps/wikijs/b
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wiki-s
  namespace: flux-system
spec:
  dependsOn:
  - name: wikijs-b
    namespace: flux-system
  interval: 11m30s
  sourceRef:
    kind: ExternalArtifact
    name: secrets
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./secrets/wikijs
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wikijs-w
  namespace: wikijs
spec:
  dependsOn:
  - name: wikijs-b
    namespace: flux-system
  - name: wikijs-s
    namespace: flux-system
  - name: gateways
    namespace: gateways
  interval: 11m26s
  sourceRef:
    kind: ExternalArtifact
    name: apps
    namespace: flux-system
  path: ./apps/wikijs/w
  prune: true
  wait: true
