#
# Mandatory for kind=Kustomization
#
#  - spec.postBuild.substitute.APPNAME
#  - spec.postBuild.substitute.NAMESPACE
#  - spec.postBuild.substitute.DATA_FOLDER
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: "${APPNAME}-scripts"
  namespace: ${NAMESPACE}
data:
  rclone-pull.sh: |
    #!/bin/sh
    set -x
    exec rclone sync -v --transfers 1 --stats 10s "rem:${NAMESPACE}/${APPNAME}" /backup
  rclone-push.sh: |
    #!/bin/sh
    set -x
    exec rclone sync -v --transfers 1 --stats 10s /backup "rem:${NAMESPACE}/${APPNAME}"
  restore-lock.sh: |
    #!/bin/sh
    echo "backup locked: follow these steps (example, may require some tuning):"
    echo "- 1. kubectl exec -it -c restore -n ${NAMESPACE} deploy/${APPNAME} -- sh"
    echo "- 2. setup '${DATA_FOLDER}' with proper contents (may be empty)"
    echo "- 3. rm -f /backup/i12e.lock (before using 'backup-one.sh' or it will lock again)"
    echo "- 4. /bin/sh /scripts/backup-one.sh"
    echo "- 5. pkill tail -> kill 'tail -f /dev/null' process to start over"
    set -x
    tail -f /dev/null &
    wait $!
    exit 1
  restore-main.sh: |
    #!/bin/sh
    set -x -e -o pipefail
    date
    ln -s /tools/restic /usr/local/bin/restic
    ln -s /tools/rclone /usr/local/bin/rclone
    date
    /bin/sh /scripts/rclone-pull.sh
    date
    [ -f "/backup/i12e.lock" ] && exec /bin/sh /scripts/restore-lock.sh
    date
    restic check
    date
    restic snapshots -g tag
    date
    restic backup -vv --tag boot "${DATA_FOLDER}"
    date
    /bin/sh /scripts/rclone-push.sh
    date
    find "${DATA_FOLDER}" -mindepth 1 -print -delete
    date
    find "${DATA_FOLDER}" -print
    date
    restic restore -vv --tag main -t / --verify latest
    date
    [ -f "${DATA_FOLDER}/.bhooks/post-restore-main.sh" ] && /bin/sh "${DATA_FOLDER}/.bhooks/post-restore-main.sh"
    date
  backup-one.sh: |
    #!/bin/sh
    set -x -e -o pipefail
    date
    [ -f "${DATA_FOLDER}/.bhooks/pre-backup-one.sh" ] && /bin/sh "${DATA_FOLDER}/.bhooks/pre-backup-one.sh"
    date
    [ -f "$${RESTIC_REPOSITORY}/config" ] || restic init
    date
    restic backup -vv --tag main "${DATA_FOLDER}"
    date
    /bin/sh /scripts/rclone-push.sh
    date
    [ -f "${DATA_FOLDER}/.bhooks/post-backup-one.sh" ] && /bin/sh "${DATA_FOLDER}/.bhooks/post-backup-one.sh"
    date
  backup-forget.sh: |
    #!/bin/sh
    set -x -e -o pipefail
    restic forget -vv -g tag -l 24 -H 48 -d 7 -w 4 -m 6 --prune
    date
    /bin/sh /scripts/rclone-push.sh
    date
  backup-at-exit.sh: |
    #!/bin/sh
    echo "Exit requested..."
    set -x -e -o pipefail
    date
    [ -f "/backup-blocked" ] && exit 0
    date
    [ -f "${DATA_FOLDER}/.bhooks/pre-backup-at-exit.sh" ] && /bin/sh "${DATA_FOLDER}/.bhooks/pre-backup-at-exit.sh"
    date
    /bin/sh /scripts/backup-one.sh
    date
    [ -f "${DATA_FOLDER}/.bhooks/post-backup-at-exit.sh" ] && /bin/sh "${DATA_FOLDER}/.bhooks/post-backup-at-exit.sh"
    date
  backup-main.sh: |
    #!/bin/sh
    set -x -e -o pipefail
    ln -s /tools/restic /usr/local/bin/restic
    ln -s /tools/rclone /usr/local/bin/rclone
    trap "exec /bin/sh /scripts/backup-at-exit.sh" TERM
    while true
    do
      date
      if [ -f "${DATA_FOLDER}/.bhooks/backup-throttle.sh" ]
      then
        /bin/sh "${DATA_FOLDER}/.bhooks/backup-throttle.sh"
      else
        sleep $((3300 + RANDOM % 600))
      fi
      date
      [ -f "/backup-blocked" ] && continue
      /bin/sh /scripts/backup-one.sh
      /bin/sh /scripts/backup-forget.sh
    done &
    wait $!
  sqlite3-wait.sh: |
    #!/bin/sh
    TARGET_DIR="$${1}"
    TOT=15
    set -e -o pipefail
    if [ "$${TARGET_DIR}" = "" ]
    then
      echo "<sqlite3-wait.sh> $(date): error: TARGET_DIR undefined"
      exit 1
    fi
    for i in $(seq 1 $${TOT})
    do
      PENDING_FILES="$(find "$${TARGET_DIR}" -type f \( -name "*-wal" -o -name "*-shm" \) -size +0c)"
      if [ -z "$${PENDING_FILES}" ]
      then
        echo "<sqlite3-wait.sh> $(date): ($${i}/$${TOT}) all SQLite files released"
        exit 0
      fi
      if [ $${i} -eq $${TOT} ]
      then
        echo "<sqlite3-wait.sh> $(date): ($${i}/$${TOT}) giving up waiting even though database seems to be opened"
      else
        echo "<sqlite3-wait.sh> $(date): ($${i}/$${TOT}) waiting for active SQLite auxiliary files to close"
      fi
      echo "$PENDING_FILES"
      echo "---"
      [ $${i} -eq $${TOT} ] && exit 0
      sleep 1
    done
