apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: anki
  namespace: flux-system
spec:
  dependsOn:
  - name: gateways
    namespace: flux-system
  interval: 11m05s
  sourceRef:
    kind: ExternalArtifact
    name: blend-scripts
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./blend/anki
  prune: true
  wait: true
  postBuild:
    substitute:
      DOCKER_IMAGE: ghcr.io/sfmunoz/anki-sync-server:25.09.2-2
      APPNAME: anki
      NAMESPACE: anki
      DATA_FOLDER: /anki_data
    substituteFrom:
      - kind: Secret
        name: routes-conf
        optional: false
