apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-rclone
  namespace: flux-system
spec:
  interval: 11m23s
  sourceRef:
    kind: ExternalArtifact
    name: blend
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./blend/csi-rclone
  prune: true
  wait: true
