apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${DOMAIN}"
  namespace: cert-manager
spec:
  secretName: "${DOMAIN}"
  issuerRef:
      name: "${ISSUER}"
      kind: Issuer
  dnsNames:
      - "${DOMAIN}"
      - '*.${DOMAIN}'
  secretTemplate:
      annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: i12e
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: i12e
