---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-secrets
  namespace: flux-system
spec:
  interval: 29m07s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/sfmunoz/i12e-secrets.git
