#
# https://fluxcd.io/flux/components/helm/
#   https://fluxcd.io/flux/components/helm/helmreleases/
# https://fluxcd.io/flux/guides/helmreleases/
# https://fluxcd.io/flux/use-cases/helm/
#

apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: wikijs
  namespace: flux-system
spec:
  interval: 25h22m
  url: oci://ghcr.io/sfmunoz/wikijs
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: 0.0.1
