apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-crds
  namespace: flux-system
spec:
  interval: 36h12m15s
  sourceRef:
    kind: ExternalArtifact
    name: blend
    namespace: flux-system
  path: ./blend/traefik-crds
  prune: false   # don't delete CRDs if removed from Git
  wait: true     # block dependents until CRDs are established
