package mesh

import (
	"fmt"
	"os"
	"os/exec"
	"slices"
	"strings"

	"github.com/sfmunoz/i12e/internal/cmdutil"
	"github.com/sfmunoz/i12e/internal/mesh/node"
	"github.com/sfmunoz/logit"
)

var log = logit.Logit().WithLevel(logit.LevelInfo)

const remMeshBase = "rem:mesh" // FIXME unhardcode this

type Mesh struct {
	remBase  string
	nodeList []*node.Node
}

func (m *Mesh) getNodeList() error {
	cmd := exec.Command("rclone", "lsf", "-R", "--files-only", m.remBase)
	bo, be, err := cmdutil.RunSimple(cmd)
	if err != nil {
		return fmt.Errorf("'rclone lsf' failed': %s (stdout=%s, stderr=%s)", err, bo.String(), be.String())
	}
	entries := strings.Split(strings.TrimSpace(bo.String()), "\n")
	slices.Sort(entries)
	slices.Reverse(entries)
	nodeNameLast := ""
	for _, entry := range entries {
		n, err := node.NewNode(node.WithRemote(entry))
		if err != nil {
			log.Error("'getNodeRemote()' failed", "err", err, "entry", entry)
			continue
		}
		nodeName := n.GetNodeName()
		if nodeName == nodeNameLast {
			continue
		}
		nodeNameLast = nodeName
		m.nodeList = append(m.nodeList, n)
	}
	return nil
}

func (m *Mesh) nodeListSetNodeLocal(nodeLocal *node.Node) error {
	nodeIdLocal := nodeLocal.GetNodeId()
	for i, n := range m.nodeList {
		if n.GetNodeId() != nodeIdLocal {
			continue
		}
		m.nodeList[i] = nodeLocal
		return nil
	}
	return fmt.Errorf("nodeListSetNodeLocal(): missing nodeLocal in nodeList")
}

func (m *Mesh) ifacePeersConfig() error {
	for _, n := range m.nodeList {
		if n.GetLocal() {
			log.Info("skipping local node", "node", n)
			continue
		}
		cmd := exec.Command(
			"wg", "set", node.GetNodeInterface(),
			"peer", n.GetWgKey().GetPubKey().B64(),
			"endpoint", n.GetWgEndpoint().String(),
			"allowed-ips", fmt.Sprintf("%s/32", n.GetNodeIP()),
		)
		bo, be, err := cmdutil.RunSimple(cmd)
		if err != nil {
			return fmt.Errorf("'wg set' failed': %s (stdout=%s, stderr=%s)", err, bo.String(), be.String())
		}
	}
	return nil
}

func (m *Mesh) etcHostsUpdate() error {
	// Flatcar's default
	lines := []string{
		"#",
		"# autogenerated by i12e - do not edit",
		"#",
		"",
		"127.0.0.1 localhost",
		"::1 localhost",
	}
	for _, n := range m.nodeList {
		lines = append(lines, fmt.Sprintf("%s %s", n.GetNodeIP(), n.GetNodeName()))
	}
	lines = append(lines, "") // NL to the end
	buf := strings.Join(lines, "\n")
	return os.WriteFile("/etc/hosts", []byte(buf), 0644)
}

func (m *Mesh) run() error {
	nodeLocal, err := node.NewNode(node.WithLocal())
	if err != nil {
		return err
	}
	if err := nodeLocal.PushToRemote(m.remBase); err != nil {
		return err
	}
	if err := nodeLocal.PurgeFromRemote(m.remBase); err != nil {
		return err
	}
	if err := m.getNodeList(); err != nil {
		return err
	}
	if err := m.nodeListSetNodeLocal(nodeLocal); err != nil {
		return err
	}
	if err := nodeLocal.HostnameConfig(); err != nil {
		return err
	}
	if err := nodeLocal.IfaceLocalConfig(); err != nil {
		return err
	}
	if err := m.ifacePeersConfig(); err != nil {
		return err
	}
	if err := m.etcHostsUpdate(); err != nil {
		return err
	}
	return nil
}

func newMesh(remBase string) *Mesh {
	nodeList := make([]*node.Node, 0)
	return &Mesh{remBase, nodeList}
}

func Run() error {
	return newMesh(remMeshBase).run()
}
