package mesh

import (
	"fmt"
	"os"
	"os/exec"
	"slices"
	"strings"

	"github.com/sfmunoz/i12e/internal/cmdutil"
	"github.com/sfmunoz/logit"
)

var log = logit.Logit().WithLevel(logit.LevelInfo)

const remMeshBase = "rem:mesh" // FIXME unhardcode this

type Mesh struct {
	nodeLocal *node
}

func (m *Mesh) getNodeList() ([]*node, error) {
	cmd := exec.Command("rclone", "lsf", "-R", "--files-only", remMeshBase)
	bo, be, err := cmdutil.RunSimple(cmd)
	if err != nil {
		return nil, fmt.Errorf("'rclone lsf' failed': %s (stdout=%s, stderr=%s)", err, bo.String(), be.String())
	}
	entries := strings.Split(strings.TrimSpace(bo.String()), "\n")
	slices.Sort(entries)
	slices.Reverse(entries)
	nodeList := make([]*node, 0)
	nodePathLocal := m.nodeLocal.getNodePath()
	nodePathLast := ""
	for _, entry := range entries {
		node, err := getNodeRemote(entry)
		if err != nil {
			log.Error("'getNodeRemote()' failed", "err", err, "entry", entry)
			continue
		}
		nodePath := node.getNodePath()
		if nodePath == nodePathLast {
			continue
		}
		nodePathLast = nodePath
		if nodePath == nodePathLocal {
			nodeList = append(nodeList, m.nodeLocal)
		} else {
			nodeList = append(nodeList, node)
		}
	}
	return nodeList, nil
}

func (m *Mesh) ifacePeersConfig(nodeList []*node) error {
	for _, node := range nodeList {
		if node.getLocal() {
			log.Info("skipping local node", "node", node)
			continue
		}
		endPoint := node.getWgEndpoint()
		if len(endPoint) < 1 {
			return fmt.Errorf("'node.getWgEndpoint()' returned empty data")
		}
		cmd := exec.Command(
			"wg", "set", nodeInterface,
			"peer", node.getWgKey().GetPubKey().B64(),
			"endpoint", endPoint,
			"allowed-ips", fmt.Sprintf("%s/32", node.getNodeIP()),
		)
		bo, be, err := cmdutil.RunSimple(cmd)
		if err != nil {
			return fmt.Errorf("'wg set' failed': %s (stdout=%s, stderr=%s)", err, bo.String(), be.String())
		}
	}
	return nil
}

func (m *Mesh) etcHostsUpdate(nodeList []*node) error {
	// Flatcar's default
	lines := []string{
		"#",
		"# autogenerated by i12e - do not edit",
		"#",
		"",
		"127.0.0.1 localhost",
		"::1 localhost",
	}
	for _, node := range nodeList {
		lines = append(lines, fmt.Sprintf("%s %s", node.getNodeIP(), node.getNodeName()))
	}
	lines = append(lines, "") // NL to the end
	buf := strings.Join(lines, "\n")
	return os.WriteFile("/etc/hosts", []byte(buf), 0644)
}

func (m *Mesh) run() error {
	if err := m.nodeLocal.hostnameConfig(); err != nil {
		return err
	}
	if err := m.nodeLocal.pushToRemote(); err != nil {
		return err
	}
	if err := m.nodeLocal.ifaceLocalConfig(); err != nil {
		return err
	}
	nodeList, err := m.getNodeList()
	if err != nil {
		return err
	}
	if err := m.ifacePeersConfig(nodeList); err != nil {
		return err
	}
	if err := m.etcHostsUpdate(nodeList); err != nil {
		return err
	}
	return nil
}

func newMesh() (*Mesh, error) {
	nodeLocal, err := getNodeLocal()
	if err != nil {
		return nil, err
	}
	return &Mesh{nodeLocal: nodeLocal}, nil
}

func Run() error {
	mesh, err := newMesh()
	if err != nil {
		return err
	}
	return mesh.run()
}
