apiVersion: v1
kind: ConfigMap
metadata:
  name: job-files
  namespace: fake
  labels:
    app: fake-alerts
data:
  run_py: |
    #!/usr/bin/env python3
    from datetime import datetime, timedelta, UTC
    from math import floor
    from json import dumps as json_dumps, loads as json_loads
    from http.client import HTTPConnection
    def main():
        rfc3339_fmt = "%Y-%m-%dT%H:%M:%SZ"
        ts_now = datetime.now(UTC)
        epoch_now = floor(ts_now.timestamp())
        block = ( epoch_now // 60 ) % 3
        ts_starts_at = ts_now - timedelta(minutes=3)
        ts_ends_at = ts_now + timedelta(minutes=15)
        body = [
          {
            "labels": {
              "alertname": "fake_alert",
              "pod": "fake_pod",
              "env": "fake",
              "hhmm": ts_now.strftime("%H%M"),
              "block": "b{0}".format(block),
            },
            "annotations": {
              "from": ts_starts_at.strftime(rfc3339_fmt),
              "gen": ts_now.strftime(rfc3339_fmt),
              "to": ts_ends_at.strftime(rfc3339_fmt),
            },
            "startsAt": ts_starts_at.strftime(rfc3339_fmt),
            "endsAt": ts_ends_at.strftime(rfc3339_fmt),
            "generatorURL": "http://localhost:11111/fake-alerts",
          },
        ]
        headers = {"Content-Type":"application/json"}
        conn = HTTPConnection("prometheus-alertmanager.mon",9093)
        conn.request("POST","/api/v2/alerts",body=json_dumps(body),headers=headers)
        resp = conn.getresponse()
        print("status =",resp.status,"reason =",resp.reason)
        for k,v in resp.getheaders():
            print(k,":",v)
        buf = resp.read()
        if len(buf) < 1:
            return
        js = json_loads(buf.decode())
        print(json_dumps(js,sort_keys=True,indent=2))
    if __name__ == "__main__":
        main()

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: fake-alerts
  namespace: fake
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: fake-alerts
            image: python:3.13.10-alpine3.22
            imagePullPolicy: IfNotPresent
            command: ["python3","/job/run.py"]
            volumeMounts:
              - name: job-vol
                mountPath: /job
          restartPolicy: OnFailure
          volumes:
            - name: job-vol
              configMap:
                name: job-files
                items:
                  - key: run_py
                    path: run.py

