apiVersion: v1
kind: Namespace
metadata:
  name: fake

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-demo
  namespace: fake
  labels:
    app: httpd-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd-demo
  template:
    metadata:
      labels:
        app: httpd-demo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/port: "80"
        prometheus.io/path: /metrics
    spec:
      containers:
      - name: busybox-httpd
        image: busybox:1.37.0-musl
        command: ["/bin/sh","-c"]
        args:
        - |
          #!/bin/sh
          mkdir -p /var/www/cgi-bin
          echo "<h1>$(hostname -s)</h1>" > /var/www/index.html
          cat << __EOF_OUTER > /var/www/cgi-bin/metrics
          #!/bin/sh
          cat << __EOF
          Content-type: text/plain

          # HELP fake_httpd_load fake load on httpd server
          # TYPE fake_httpd_load gauge
          fake_httpd_load \$((10+RANDOM%20)).\$((RANDOM%10))
          __EOF
          __EOF_OUTER
          chmod 755 /var/www/cgi-bin/metrics
          cat << __EOF2 > /etc/httpd.conf
          # ref: busybox-1_37_0/networking/httpd.c
          H:/var/www
          I:index.html
          P:/metrics:http://127.0.0.1/cgi-bin/metrics
          __EOF2
          exec busybox httpd -c /etc/httpd.conf -f -p 80
        ports:
        - containerPort: 80
