apiVersion: batch/v1
kind: CronJob
metadata:
  name: fake-job
  namespace: fake
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: fake-job
            image: busybox:1.37.0-musl
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh","-c"]
            args:
            - |
              #!/bin/sh
              JOB="fake-job"
              for x in `seq 0 5`
              do
                [ $x -gt 0 ] && sleep 10
                for i in `seq 0 9`
                do
                  VAL="$((10+RANDOM%20)).$((RANDOM%10))"
                  echo "$(date): ($x) $i -> $VAL"
                  INSTANCE="inst_${i}"
                  cat << __EOF | wget -O /dev/null --post-file - "http://prometheus-prometheus-pushgateway.mon:9091/metrics/job/${JOB}/instance/${INSTANCE}"
              # HELP fake_job_load fake load on job
              # TYPE fake_job_load gauge
              fake_job_load $VAL
              __EOF
                done
              done
          restartPolicy: OnFailure
