apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web
  namespace: i12e
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rem-multi
