# https://docs.k3s.io/add-ons/helm
# https://docs.k3s.io/installation/packaged-components
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: postgres-rclone
  namespace: kube-system
spec:
  chart: oci://ghcr.io/sfmunoz/postgres-rclone
  version: "{{ .Version }}"
  targetNamespace: "{{ .Namespace }}"
  createNamespace: true
  {{- if .ValuesContent }}
  valuesContent: |-
  {{- .ValuesContent | nindent 4 }}
  {{- end }}
