apiVersion: v1
kind: Namespace
metadata:
  name: anki
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: i12e
---
apiVersion: v1
kind: Namespace
metadata:
  name: reflector
---
apiVersion: v1
kind: Namespace
metadata:
  name: csi-rclone
---
apiVersion: v1
kind: Namespace
metadata:
  name: trilium
---
apiVersion: v1
kind: Namespace
metadata:
  name: forgejo
