# Orig: https://raw.githubusercontent.com/nolar/kopf/main/peering.yaml

apiVersion: kopf.dev/v1
kind: ClusterKopfPeering
metadata:
  name: default
---
apiVersion: kopf.dev/v1
kind: KopfPeering
metadata:
  namespace: default
  name: default
