apiVersion: v1
kind: Pod
metadata:
  name: genesis
spec:
  hostPID: true
  restartPolicy: Never
  containers:
  - name: genesis
    image: ghcr.io/sfmunoz/k8s-bulk:v1.3.0
    imagePullPolicy: IfNotPresent
    command: ["python3","-u","/app/genesis.py"]
    volumeMounts:
    - mountPath: /genesis
      name: vol-host
      readOnly: false
    - mountPath: /app
      name: app-vol
  volumes:
  - name: vol-host
    hostPath:
      path: /
      type: Directory
  - name: app-vol
    configMap:
      name: genesis
      items:
      - key: genesis-py
        path: genesis.py
