apiVersion: v1
kind: Pod
metadata:
  name: genesis
spec:
  hostPID: true
  restartPolicy: Never
  containers:
  - name: genesis
    image: ghcr.io/sfmunoz/k8s-bulk:v1.3.0
    imagePullPolicy: IfNotPresent
    command: ["python3","-u","-c"]
    args:
    - |
      {{- include "genesis.py" . | nindent 6 }}
    volumeMounts:
    - mountPath: /genesis
      name: vol-host
      readOnly: false
  volumes:
  - name: vol-host
    hostPath:
      path: /
      type: Directory
