apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: genesis
data:
  ssh_authorized_keys: {{ join "\n" .Values.os.ssh_authorized_keys | trim | required "os.ssh_authorized_keys is empty" | b64enc }}
