apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
  - name: cert-manager-install
    namespace: flux-system
  interval: 10m38s
  sourceRef:
    kind: ExternalArtifact
    name: blend
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./blend/cert-manager
  prune: true
  timeout: 10m
  wait: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: certs-conf
        optional: false
