name: release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: actions/setup-go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'
          cache: true

      - name: go mod download
        run: go mod download

      - name: build.sh
        run: bash scripts/build.sh

      - name: release-notes
        uses: sfmunoz/actions/release-notes@v1
        with:
          output_file: dist/notes.md

      - name: release-notes-patch
        run: |
          set -x -e -o pipefail
          awk '/## Changelog/ {
            printf("Install (devel):\n```\n$ go run main.go butane | ssh core@192.168.56.51 bash\n```\n\n## Changelog\n")
            next
          } { print }' dist/notes.md

      - name: gh-release-create
        run: |
          set -x -e -o pipefail
          gh release create "${GITHUB_REF_NAME}" \
            --title "${GITHUB_REF_NAME}" \
            --verify-tag \
            --notes-file dist/notes.md \
            dist/i12e-flatcar.raw \
            dist/i12e-flatcar.raw.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
