name: release

on:
  push:
    tags: ["v*"]
  #push:
  #  branches: ["main"]
  #pull_request:
  #  branches: ["main"]
  #workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: actions/setup-go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'
          cache: true

      #- name: go mod tidy
      #  run: go mod tidy

      - name: go mod download
        run: go mod download

      - name: build.sh
        run: bash scripts/build.sh

      - name: release-notes.py
        run: |
          set -x -e -o pipefail
          curl -O https://raw.githubusercontent.com/sfmunoz/github-playground/refs/tags/v0.0.29/scripts/release-notes.py | python3 - dist/notes.md

      - name: gh-release-create
        run: |
          set -x
          gh release create "${GITHUB_REF_NAME}" \
            --title "${GITHUB_REF_NAME}" \
            --verify-tag \
            --notes-file dist/notes.md \
            dist/*.raw dist/*.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
